// <auto-generated />
using MDCForms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDCForms.Migrations
{
    [DbContext(typeof(MDCFormsContext))]
    partial class MDCFormsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MDCForms.Models.Companies", b =>
                {
                    b.Property<string>("CompanyName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("DistType")
                        .HasColumnType("int");

                    b.HasKey("CompanyName");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MDCForms.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CompaniesCompanyName")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CompaniesCompanyName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MDCForms.Models.Products", b =>
                {
                    b.HasOne("MDCForms.Models.Companies", "Companies")
                        .WithMany()
                        .HasForeignKey("CompaniesCompanyName");

                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
