//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartsDetail
    {
        public int CartId { get; set; }
        public int SubServiceId { get; set; }
        public int ClientId { get; set; }
    
        public virtual SubService SubService { get; set; }
        public virtual TblClient TblClient { get; set; }
    }
}
