//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExcellOnServiceEntities : DbContext
    {
        public ExcellOnServiceEntities()
            : base("name=ExcellOnServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartsDetail> CartsDetails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<PymentDetail> PymentDetails { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SubService> SubServices { get; set; }
        public virtual DbSet<TblClient> TblClients { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
    }
}
