//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PymentDetail
    {
        public int PaymentId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardCvv { get; set; }
        public string Address { get; set; }
        public int ClientId { get; set; }
        public string Phone { get; set; }
    
        public virtual TblClient TblClient { get; set; }
    }
}
