//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubService()
        {
            this.CartsDetails = new HashSet<CartsDetail>();
        }
    
        public int SubServiceId { get; set; }
        public string SubServiceName { get; set; }
        public string ServiceImage { get; set; }
        public string SubServiceDescription { get; set; }
        public string SubServiceCode { get; set; }
        public int SubServiceCharges { get; set; }
        public int ServiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartsDetail> CartsDetails { get; set; }
        public virtual Service Service { get; set; }
    }
}
